export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";

//Campaign constants
export const ERROR = "ERROR";
export const MAKE_REQUEST = "MAKE_REQUEST";
export const GET_CAMPAIGNS = "GET_CAMPAIGNS";
export const ADD_CAMPAIGNS = "ADD_CAMPAIGNS";
export const EDIT_CAMPAIGN = "EDIT_CAMPAIGN";
export const END_CAMPAIGN = "END_CAMPAIGN";
export const ADD_CATEGORY_TO_CAMPAIGN = "ADD_CATEGORY_TO_CAMPAIGN";
export const ADD_EVENT_TO_CAMPAIGN = "ADD_EVENT_TO_CAMPAIGN";
export const CANCEL_CAMPAIGN = "CANCEL_CAMPAIGN";
export const EVENT_UNDER_CAMPAIGNS = "EVENT_UNDER_CAMPAIGNS";
export const GET_CAMPAIGNS_PER_ID = "GET_CAMPAIGNS_PER_ID";
export const EDIT_EVENT = "EDIT_EVENT";
export const GET_EVENTS_PER_ID = "GET_EVENTS_PER_ID";
export const GET_CURR_CAMPAIGNS = "GET_CURR_CAMPAIGNS";
export const GET_SHORTLISTED_CUSTOMERS = "GET_SHORTLISTED_CUSTOMERS";
export const GET_WiNNERS = "GET_WiNNERS";


//Draws
export const DRAWS_ERROR = "DRAWS_ERROR";
export const MAKE_DRAWS_REQUEST = "MAKE_DRAWS_REQUEST";
export const GET_DRAWS = "GET_DRAWS";
export const GET_DRAWS_BY_ID = "GET_DRAWS_BY_ID";
export const DRAWS_EVENT_SUMMARY = "DRAWS_EVENT_SUMMARY";
export const PERFORM_DRAW = "PERFORM_DRAW";
export const RUN_DRAWS = "RUN_DRAWS";
export const SAVE_WINNERS = "SAVE_WINNERS";

//USER PROFILE
export const PROFILE_ERROR = "PROFILE_ERROR";
export const MAKE_PROFILE_REQUEST = "MAKE_PROFILE_REQUEST";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_BY_USERNAME = "GET_USER_PROFILE_BY_USERNAME";
export const ADD_USER_PROFILE = "ADD_USER_PROFILE";
